name: Mirror

# Mirrors the Altium 365 hosted repository to GitHub every six hours.

# ! Note: The ALTIUM_SUERNAME secret should encode '@' as '%40'.

on:
  schedule:
    - cron: "0 */6 * * *"
  push:
    paths:
      - ".github/workflows/mirror.yml"
  workflow_dispatch:

jobs:
  Mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Altium Repository
        run: git clone --mirror https://${{secrets.ALTIUM_USERNAME}}:${{secrets.ALTIUM_TOKEN}}@afs-vcs-eu1.365.altium.com/git/A88AC864-7F10-477D-A582-77F547FCAFC0.git SISPS-PV-PCB

      - name: Set GitHub Push URL
        working-directory: SISPS-PV-PCB
        run: |
          git remote set-url --add --push origin https://LawrenceStanton:${{secrets.WORKFLOW_TOKEN}}@github.com/LawrenceStanton/SISPS-PV-PCB.git

      - name: Push to GitHub
        working-directory: SISPS-PV-PCB
        run: git push --mirror
